# Generated by Django 2.2.4 on 2020-02-16 06:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(default='', upload_to=users.models.user_directory_save_file),
        ),
    ]
