# Generated by Django 2.2.4 on 2020-02-18 08:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(default='default.csv', upload_to=users.models.user_directory_save_file),
        ),
    ]
