# Generated by Django 2.2.10 on 2020-02-27 12:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200218_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.user_directory_save_file),
        ),
    ]
